#!/usr/bin/env ruby

require 'rubygems'
require 'irb'
require 'irb/completion'
$:.unshift File.join(File.dirname(__FILE__), '..', 'lib')
require 'parser'
$LOAD_PATH[0,0] = File.join(File.dirname(__FILE__), '..', 'lib')
require 'mongo'
include Mongo

ARGV.concat [ "--readline", "--prompt-mode", "simple" ]

class Object
  # Метод для быстрой справки по методам текущего объекта
  def m
    if [Module, Class].include? self.class
      public_methods - self.class.public_instance_methods
    else
      class << self
        self.public_instance_methods false
      end
    end
  end  
end

module Kernel
  # Перезагружаем все файлы (чтобы не перезапускать консоль в случае редактирования кода)
  def reload
    Dir.glob('lib/**/*.rb').each {|file| load file }
  end
end



# Insert 3 records
# 3.times { |i| coll.insert({'title' => i+1}) }

# puts "There are #{coll.count()} records in the test collection. Here they are:"
# coll.find().each { |doc| puts doc.inspect }

# Destroy the collection
# coll.drop

IRB.start